### ISSUE TITLE
var-file does not correctly add HCL variables

### ISSUE THREAD

**Issue by jeremygaither** [rgreinho/tfe-cli#13]
Provided a var-file such as this:

```hcl
regular_string = "foo"
list_things = [
  "apple", 
  "banana", 
  "hippo"
]
```

The variable `list_things` is inserted as a regular variable that looks like this: `[apple banana hippo]` instead of proper HCL.

**Comment by rgreinho** [comment]
Yeah, the `--var-file` flag only supports regular non-sensitive variables. 

I'll try to see if I can change that.

**Comment by jeremygaither** [comment]
They are non-sensitive variables, but they need to get encoded as HCL and set as HCL variables.

**Comment by rgreinho** [comment]
Done in PR #14.
