### ISSUE TITLE
Allow specifying organization as part of workspace name

### ISSUE THREAD

**Issue by ss-remygreinhofer** [rgreinho/tfe-cli#5]
Current Behavior
----------------

Currently the organization and the workspace have to be specified using 2 different arguments.

Expected Behavior
-----------------

Allow specifying organization as part of workspace name, eg: some-org/some-workspace where the org and workspace name are separated with a URI forward slash.

Possible Solution
-----------------

Try to split the organization name with a `/`. If it works, it means the second part is the workspace.

**Comment by jeremygaither** [comment]
It would also be handy to specify the org as an environment variable too. I should probably open as a separate issue...

**Comment by rgreinho** [comment]
You can specify the organization via `TFE_ORG`.
